<?php
$propdefs = array(
    'id' => array(
        'name' => 'id',
        'source' => 'db',
        'datatype' => 'string',
        'fieldtype' => 'hidden',
        'defaultvalue' => null,
        'required' => true,
        'label' => 'id',
        'len' => '16',
        'searchable' => true,
        'isPrimary' => true,
    ),
    'title' => array(
        'name' => 'title',
        'source' => 'db',
        'datatype' => 'string',
        'fieldtype' => 'text',
        'defaultvalue' => null,
        'required' => true,
        'label' => 'Title',
        'len' => '255',
        'searchable' => true,
        'link' => true,
    ),
    'description' => array(
        'name' => 'description',
        'source' => 'db',
        'datatype' => 'string',
        'fieldtype' => 'text',
        'defaultvalue' => null,
        'required' => false,
        'label' => 'Synopsis',
        'len' => '65535',
        'searchable' => true,
    ),
    'tagline' => array(
        'name' => 'tagline',
        'source' => 'db',
        'datatype' => 'string',
        'fieldtype' => 'text',
        'defaultvalue' => null,
        'required' => false,
        'label' => 'Tagline',
        'len' => '1000',
        'searchable' => true,
    ),
    'release_date' => array(
        'name' => 'release_date',
        'source' => 'db',
        'datatype' => 'date',
        'fieldtype' => 'date',
        'defaultvalue' => null,
        'required' => false,
        'label' => 'Release Date',
        'len' => '1000',
        'searchable' => true,
    ),
);